### ISSUE TITLE
doesn't work with babel 7.x

### ISSUE THREAD

**Issue by obilodeau** [Mogztter/asciidoctor-reveal.js-integration-babel#1]
Or there is something I don't understand :laughing: 

Stack trace I'm getting:
```
$ npm test

> asciidoctor-reveal.js-integration-babel@1.0.0 test /home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel
> babel --presets env main.js -o dist/main.js && node dist/main.js

Error: Cannot find module 'babel-preset-env' from '/home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel'
- Did you mean "@babel/env"?
    at Function.module.exports [as sync] (/home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel/node_modules/resolve/lib/sync.js:74:15)
    at resolveStandardizedName (/home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /home/olivier/src/asciidoc/asciidoctor-reveal.js/test/js-babel/node_modules/@babel/core/lib/config/config-descriptors.js:58:96 {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! Test failed.  See above for more details.
```

Trying to apply this patch to `package.json`:
```patch
$ git diff package.json
diff --git a/test/js-babel/package.json b/test/js-babel/package.json
index 85361b7..45a19e1 100644
--- a/test/js-babel/package.json
+++ b/test/js-babel/package.json
@@ -18,10 +18,11 @@
   },
   "homepage": "https://github.com/Mogztter/asciidoctor-reveal.js-integration-babel#readme",
   "devDependencies": {
-    "babel-cli": "^6.26.0",
-    "babel-preset-env": "^1.7.0"
+    "@babel/cli": "^7.7.0",
+    "@babel/core": "^7.7.0",
+    "@babel/preset-env": "^7.7.0"
   },
   "dependencies": {
-    "asciidoctor-reveal.js": "file:../../asciidoctor-reveal.js-1.1.4-dev.tgz"
+    "asciidoctor-reveal.js": "^2.0.0"
   }
 }
```

I'm trying to get rid of security issues related to babel 6 dependencies: lodash, braces, set-value and mixin-deep.

**Comment by Mogztter** [comment]
I think you also need to update the script in the `package.json`: https://babeljs.io/docs/en/v7-migration#resolving-string-based-config-values

Didn't try but it should be:
```
$ babel --presets @babel/env main.js -o dist/main.js && node dist/main.js
```

**Comment by Mogztter** [comment]
And if you use version 2.0.0, you will need to update the `main.js` to call `register`:

```js
import Asciidoctor from 'asciidoctor.js'
import AsciidoctorReveal from 'asciidoctor-reveal.js'

const asciidoctor = Asciidoctor()
AsciidoctorReveal.register()
```

**Comment by Mogztter** [comment]
- Upgrade to Babel 7 + fix security issues: https://github.com/Mogztter/asciidoctor-reveal.js-integration-babel/pull/2
- All of the above + upgrade to asciidoctor-reveal.js 2.0+: https://github.com/Mogztter/asciidoctor-reveal.js-integration-babel/pull/3

**Comment by obilodeau** [comment]
Implemented it in two separate commits like you did to give users a chance to see the 1.x API in the git history. Great idea and thanks for your help as always!

PR: https://github.com/asciidoctor/asciidoctor-reveal.js/pull/285
